-- phpMyAdmin SQL Dump
-- version 4.5.4.1deb2ubuntu2
-- http://www.phpmyadmin.net
--
-- Client :  localhost
-- Généré le :  Ven 31 Mars 2017 à 11:37
-- Version du serveur :  5.7.17-0ubuntu0.16.04.1
-- Version de PHP :  7.0.15-0ubuntu0.16.04.4

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données :  `apym`
--

-- --------------------------------------------------------

--
-- Structure de la table `hymn`
--

CREATE TABLE `hymn` (
  `id` int(11) NOT NULL,
  `title` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `num` varchar(5) COLLATE utf8_unicode_ci NOT NULL,
  `ref` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `lyrics` longtext COLLATE utf8_unicode_ci NOT NULL,
  `musical_part_id` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Contenu de la table `hymn`
--

INSERT INTO `hymn` (`id`, `title`, `num`, `ref`, `lyrics`, `musical_part_id`) VALUES
(1, 'Éternel, c’est à Toi', '1', 'Ps 28', 'Éternel, c’est à Toi que je crie.<br>Mon rocher ne reste pas sourd !<br>Ne T’éloigne pas sans me répondre,<br>Je serais semblable à ceux<br>Qui descendent dans la fosse !<br><br>Quand je crie à Toi,<br>Quand j’élève les mains vers Ton sanctuaire<br>Écoute la voix de mes supplications !<br>Éternel, c’est à Toi que je crie<br>Mon rocher ne reste pas sourd !<br>Ne T’éloigne pas sans me répondre,<br>Je serais semblable à ceux<br>Qui descendent dans la fosse !<br><br>Béni soit le Nom de l’Éternel,<br>Car Il exauce ma voix !<br>Il est ma force et mon bouclier,<br>En Lui mon cœur se confie<br>Et je suis secouru.<br>J’ai de l’allégresse dans le cœur,<br>Et je Le loue par mes chants.<br>Il est la force de son peuple,<br>Le rocher des délivrances, des délivrances !<br>', NULL),
(2, 'La solitude', '2', 'Es 35', '<span style=\'padding-left:15px\'></span>La solitude s’égaiera, comme un narcisse fleurira<br><span style=\'padding-left:15px\'></span>Et couverte de belles fleurs, elle tressaillira de bonheur<br><br>Car des eaux couleront dans le désert,<br>Et des ruisseaux dans la solitude.<br>Le mirage se changera en étang,<br>La terre desséchée en sources d’eaux.<br><br>Il y aura un chemin tout tracé,<br>Une route appelée la voie sainte,<br>Les saints de l’Éternel y marcheront,<br>Les insensés ne pourront s’égarer.<br><br>L’allégresse et la joie s’approcheront,<br>Douleurs, gémissements s’enfuiront.<br>Comme un fleuve sera tout leur bonheur,<br>L’éternelle joie les couronnera.<br>', NULL),
(3, 'Pourquoi crains-tu, mon âme ?', '3', 'Ca 50', 'Pourquoi crains-tu, mon âme ? Au fort de la souffrance,<br>Le Seigneur n’est-il pas ton appui, ton soutien ?<br>Élève en haut les yeux; Il est ta délivrance.<br>Il ne te laisse pas : mon âme, ne crains rien !<br><br>Qu’il me faille affronter tourments, combats, épreuves,<br>Passer par le creuset où l’on affine l’or,<br>Entrer dans la fournaise ou traverser les fleuves,<br>Il reste mon Sauveur, mon guide, mon trésor.<br><br>Non, je ne craindrai rien ! Ni Satan, ni le monde<br>Ne peuvent me ravir des bras du Bon Berger.<br>Là je savoure en paix sa charité profonde.<br>Là je suis pour toujours à l’abri du danger.<br>', NULL),
(4, 'Jésus, divin modèle', '4', 'CV 31B', '<span style=\'padding-left:15px\'></span>Jésus, divin modèle de douceur et de paix,<br><span style=\'padding-left:15px\'></span>Ta sainte voix m’appelle à marcher, désormais<br><span style=\'padding-left:15px\'></span>Dans ce sentier de grâce, de support, de bonté,<br><span style=\'padding-left:15px\'></span>Où Tu laissas la trace de ton humilité.<br><br>Tu passas sur la terre, dans l’ineffable amour,<br>Que toute ta carrière a montré chaque jour.<br>Tu nous dis : "Je vous aime, nul n’aime comme Moi.<br>Enfants, faites de même, car l’amour est ma loi".<br><br>Que mon esprit se range à cette loi d’amour<br>Pour vivre à Ta louange, d’un cœur droit sans détour<br>Comme Toi, charitable, patient, humble et doux<br>Saint, pur, irréprochable, faisant du bien à tous<br>', NULL),
(5, 'Seigneur, je veux te suivre', '5', 'null', 'Seigneur, je veux Te suivre, et sans impatience,<br>Le front toujours serein, ne regarder qu\'à Toi.<br>Trouver dans cette épreuve un peu plus de science<br>Pour vivre de Ta grâce et marcher par la foi.<br><br><span style=\'padding-left:15px\'></span>Viens donc mettre une fin au charnel ministère<br><span style=\'padding-left:15px\'></span>Qui me barre l’accès des œuvres de l’Esprit.<br><span style=\'padding-left:15px\'></span>J’accepte de la croix le souverain cautère.<br><span style=\'padding-left:15px\'></span>J’accepte tout, Seigneur, je veux être guéri.<br><br>Je ne veux plus subir le joug de l’habitude,<br>Ni croire que l’Esprit a cessé d’inspirer.<br>Je ne veux redouter aucune certitude,<br>Ni craindre qu’avec Toi je puisse m’égarer.<br><br>Je ne veux surtout pas avoir le bruit de vivre<br>Sans les fleuves d’eau vive et la fécondité.<br>Je ne veux pas qu’on pense en me voyant te suivre<br>Qu’en vain je me prévaux de ta fidélité.<br>', NULL),
(6, 'Rendez grâces avec joie', '6', 'Cl 1', '<span style=\'padding-left:15px\'></span>Rendez grâces avec joie, rendez grâces avec joie<br><span style=\'padding-left:15px\'></span>Au Père, au Père, qui vous a rendus capables<br><span style=\'padding-left:15px\'></span>D’avoir part, d’avoir part à l’héritage<br><span style=\'padding-left:15px\'></span>Des saints dans la lumière !<br><br>Il nous a délivrés de la puissance des ténèbres.<br>Il nous a transportés dans le royaume de Son Fils bien-aimé<br>En qui nous avons la rédemption, le pardon des péchés,<br>Nous, qui par nos œuvres mauvaises, étions autrefois ennemis.<br><br>Dieu a voulu, par Lui, tout réconcilier avec Lui-même,<br>Faisant la paix par Lui.<br>Oui, la paix par Lui, par le sang de Sa croix,<br>Pour nous faire paraître devant Lui sans reproche et saints,<br>Si du moins nous demeurons fondés, inébranlables dans la foi.<br>', NULL),
(7, 'Quand je contemple', '7', 'Ps 8', '<span style=\'padding-left:15px\'></span>Quand je contemple les cieux, ouvrage de tes mains,<br><span style=\'padding-left:15px\'></span>La lune et les étoiles que tu as créées,<br><span style=\'padding-left:15px\'></span>Qu’est-ce que l’homme, pour que tu te souviennes de lui ?<br><span style=\'padding-left:15px\'></span>Et le fils de l’homme<br><span style=\'padding-left:15px\'></span>Pour que Tu prennes garde à lui ? (fin : bis)<br><br>Tu l’as fait de peu inférieur à Toi.<br>Tu l’as couronné de gloire.<br>Tu lui as donné la domination.<br>Tu as tout placé sous ses pieds;<br>Les brebis et les bœufs, les animaux des champs,<br>Tous les oiseaux du ciel, les poissons de la mer.<br><br>Seigneur, mon rocher, mon libérateur,<br>Que Ton nom est magnifique !<br>Dans les cieux s’élève ta majesté,<br>Ils racontent ta puissance.<br>Tu confonds l’ennemi, tu fermes sa bouche.<br>Tu brises sa tête; il demeure vaincu.<br>', NULL),
(8, 'Dieu est ma délivrance', '8', 'Es 12', 'Dieu est ma délivrance, je serai plein de confiance.<br>Je ne craindrai donc rien.<br>L\'Éternel est ma force et le sujet de mes louanges.<br>C’est Lui qui m’a sauvé.<br>Vous irez puiser de l’eau avec joie aux sources du salut (bis)<br>Louez l\'Éternel, invoquez son nom !<br>Publiez ses œuvres parmi les nations !<br>Poussez des cris de joie, héritiers du pardon !<br>', NULL),
(9, 'Bienheureux ceux qui placent', '9', 'Ps 84', '<span style=\'padding-left:15px\'></span>Bienheureux ceux qui placent en Toi leur appui !<br><span style=\'padding-left:15px\'></span>Ils trouvent dans leur cœur des chemins tout tracés.<br><span style=\'padding-left:15px\'></span>Leur force toujours augmente pendant la marche.<br><br>Oh ! Que tes demeures sont aimables.<br>Eternel, mon âme soupire, languit de tes parvis.<br>Mon cœur et ma chair poussent des cris vers mon Dieu.<br>Éternel, mon Dieu, écoute donc ma prière !<br><br>Le passereau lui-même trouve une maison.<br>L’hirondelle un nid pour y mettre ses petits.<br>Heureux sont tous ceux qui habitent ta maison !<br>Ils peuvent te célébrer encore et toujours.<br><br>Mon Dieu est un soleil et un sûr bouclier.<br>Il ne refuse aucune bonté aux intègres.<br>L’Éternel dispense la grâce et la gloire.<br>Heureux celui qui met en Toi sa confiance !<br><br>Mieux vaut un jour dans tes parvis que mille ailleurs.<br>Je préfère rester au seuil de Ta maison,<br>Plutôt que d’habiter le palais des méchants.<br>Car dans ta présence, ô Dieu, j’aime me trouver !<br>', NULL),
(10, 'Avec des cris de joie', '10', 'Ps 63', '<span style=\'padding-left:15px\'></span>Avec des cris de joie ma bouche chantera,<br><span style=\'padding-left:15px\'></span>J’élèverai mes mains et Te célébrerai.<br><span style=\'padding-left:15px\'></span>(bis)<br><br>Ô Dieu, Tu es mon Dieu, mon âme te recherche<br>Et soupire après Toi sur la terre desséchée.<br><br>Lorsque je pense à Toi, esseulé sur ma couche,<br>Je médite sur Toi les veilles de la nuit.<br><br>Je connais le bonheur à l’ombre de tes ailes,<br>Car Tu es mon secours, ta droite me soutient.<br><br>J’aime te contempler quand dans ton sanctuaire<br>Ta gloire resplendit, ta puissance se révèle.<br><br>', NULL),
(11, 'Je louerai l\'Éternel', '11', 'Ps 9', 'Je louerai l\'Éternel de tout mon cœur,<br>Je raconterai tout, toutes Tes merveilles,<br>Je ferai de Toi le sujet de ma joie et de mon allégresse.<br>Je chanterai Ton nom, Dieu Très-Haut, Dieu Très-Haut !<br>', NULL),
(12, 'Aujourd’hui, c’est encore un jour', '12', 'CGG 77', 'Aujourd’hui, c\'est encore un jour où Dieu fait grâce,<br>Où son appel d’amour te convie à la croix.<br>C’est le jour du salut: près de toi, Jésus passe.<br>Oh ! Réponds, sans tarder, à sa divine voix.<br><br>Aujourd’hui, c’est encore un jour où la lumière<br>Peut descendre du ciel jusqu’au fond de ton cœur;<br>Laisse-Lui révéler ta profonde misère,<br>Et viens la déposer à la croix du Sauveur.<br><br>Aujourd’hui, c’est encore un jour où Dieu délivre,<br>Où de l’esclave Il fait un fils de Sa maison.<br>Désormais, si tu veux, libre tu pourras vivre,<br>Car Jésus a payé le prix de ta rançon.<br><br>Aujourd’hui, retentit encore le beau message<br>De la grâce de Dieu, de Son immense amour.<br>Si tu veux croire enfin, le divin héritage<br>Sera ta part heureuse au céleste séjour.<br>', NULL),
(13, 'Mon Dieu sonde-moi', '13', 'Ps', 'Mon Dieu, sonde-moi et connais mon cœur;<br>Éprouve-moi et connais mes pensées !<br>Et si je suis sur la mauvaise voie,<br>Conduis-moi donc sur la voie de l’éternité !<br><br><span style=\'padding-left:15px\'></span>C’est vers Toi, Éternel, que se tournent mes yeux,<br><span style=\'padding-left:15px\'></span>C’est auprès de Toi que je cherche un refuge,<br><span style=\'padding-left:15px\'></span>N’abandonne pas mon âme ! (bis)<br><span style=\'padding-left:15px\'></span>(Car aucun vivant n’est juste devant Toi.) (À la fin)<br><br>Éternel, mets une garde à ma bouche,<br>Oh veille sur la porte de mes lèvres !<br>Préserve mon cœur des choses mauvaises,<br>Ainsi que des actions qui déshonorent Ton nom !<br>', NULL),
(14, 'Mon âme, apporte au Seigneur', '14', 'null', 'Mon âme, apporte au Seigneur ta prière avec ferveur.<br>Puisqu’il t’invite à prier, il ne peut que t’écouter.<br>Tu ne peux trop demander, car Dieu peut tout te donner.<br>Oui, pour la gloire de son nom et l’honneur de sa maison !<br><br><span style=\'padding-left:15px\'></span>Toi, qui t’approches du Roi,<br><span style=\'padding-left:15px\'></span>Sans cesse rappelle-toi<br><span style=\'padding-left:15px\'></span>Que tout-puissant est ton Dieu<br><span style=\'padding-left:15px\'></span>Et qu’il fait tout ce qu’il veut<br><br>Souviens-toi que le ruisseau de l’Éternel est plein d’eau,<br>Oui, d’une eau pure qui jaillit, vivifie et rafraîchit.<br>D’abord, ôte de mon cœur mon péché, ô mon Sauveur !<br>Libère-moi, par ton sang, de ce fardeau si pesant !<br><br>Révèle en moi ton pouvoir, à chaque instant fais-moi voir<br>Tout ce que tu veux de moi. Augmente, augmente ma foi !<br>Nourris-moi de ton amour, que j’en vive chaque jour !<br>Oui, sois mon guide, mon gardien. Oh ! Tiens ma main dans ta main !<br>', NULL),
(15, 'Le ciel était voilé', '15', 'AF 504', 'Le ciel était voilé, la route était obscure.<br>Voyageur désolé, j’errais à l’aventure.<br>Chaque arbre du chemin était une menace.<br>Et je cherchais en vain la porte de la Grâce.<br><br>Enfin las et transi, je tombai sur la route<br>En disant : "C’est ici que je mourrai sans doute !",<br>Quand un rayon des cieux, pour moi perçant l’espace,<br>Vint montrer à mes yeux la porte de la Grâce.<br><br>Mais je doutais encore, se peut-il, ô merveille,<br>Que seule quand tout dort, la Grâce toujours veille ?<br>"Pitié ! Je vais mourir !" murmurai-je à voix basse.<br>Et je la vis s’ouvrir, la porte de la Grâce.<br><br>Et je vis sur le seuil, debout dans la lumière<br>Jésus ! Quel doux accueil il fit à ma misère !<br>"Je t’attendais : pourquoi, dit-il, pauvre âme lasse<br>Viens-tu si tard ? C’est Moi, c’est Moi qui suis la Grâce.<br>Pourquoi viens-tu si tard ? C’est Moi qui suis la Grâce".<br>', NULL),
(16, 'Ô mes fils, cessez d’être négligents', '16', '2 Cr 29;Hb 6', '<span style=\'padding-left:15px\'></span>Ô mes fils, cessez donc d’être si négligents,<br><span style=\'padding-left:15px\'></span>Car vous avez été choisis par l’Éternel<br><span style=\'padding-left:15px\'></span>Pour vous tenir à Son service devant Lui. (bis)<br><br>Cette espérance, vous la possédez déjà<br>Comme une ancre de l’âme, sûre et solide.<br>N’abandonnez pas cette entière assurance.<br>C’est à elle qu’est attachée la rémunération !<br>', NULL),
(17, 'Chantez à l’Éternel', '17', 'Es 42', 'Chantez à l’Éternel,<br>Chantez à l’Éternel un cantique nouveau<br>(bis)<br><br>Chantez Ses louanges, célébrez son nom<br>Jusqu’aux extrémités de la terre !<br>Du sommet des montagnes poussez des cris de joie,<br>Et rendez gloire à l’Éternel !<br>', NULL),
(18, 'Maudit soit l’homme', '18', 'Jr 17', 'Maudit soit l’homme qui se confie dans l’homme,<br>Qui prend la chair pour son appui,<br>Et qui détourne son cœur de l’Éternel !<br>Tout comme un misérable dans le désert,<br>Il ne voit point arriver le bonheur.<br>Il habite les lieux brûlés du désert,<br>Une terre salée, sans habitants.<br><br>Béni soit l’homme qui se confie en Jésus,<br>Dont l’Éternel est l’espérance,<br>Et qui recherche le Seigneur l’Éternel !<br>Il est comme un arbre planté près des eaux<br>Qui étend ses racines vers le courant.<br>Il n’aperçoit point la chaleur quand elle vient,<br>Et il ne cesse de porter du fruit.<br>', NULL),
(19, 'Vous qui passez par la souffrance', '19', 'null', 'Vous qui passez par la souffrance,<br>Meurtris sous les coups du malheur,<br>Criez au Dieu de délivrance;<br>Il apaisera vos douleurs.<br><br><span style=\'padding-left:15px\'></span>Cette lumière, c’est la Parole<br><span style=\'padding-left:15px\'></span>Du Dieu d’amour et de bonté.<br><span style=\'padding-left:15px\'></span>Oui, c’est par elle qu’il nous console.<br><span style=\'padding-left:15px\'></span>Elle seule est la vérité.<br><br>Ne restez pas dans la nuit sombre,<br>Accablés dans votre chagrin.<br>Une lumière luit dans l’ombre<br>Pour éclairer votre chemin.<br><br>N’oubliez pas que Dieu vous aime<br>Et que, pour vous, il a donné<br>Pour vous sauver, son Fils lui-même,<br>Mort sur la croix pour nos péchés.<br><br>Apportez-lui votre détresse.<br>Ne doutez pas de son amour.<br>Il est fidèle à sa promesse.<br>Comptez sur lui de jour en jour.<br>', NULL),
(20, 'Il n’avait ni beauté', '20', 'Es 53', 'Il n’avait ni beauté, aucun éclat,<br>Non, rien qui puisse attirer nos regards.<br>Son aspect n’avait rien, rien pour nous plaire.<br>Il fut l’homme de douleur et souffrant.<br><br><span style=\'padding-left:15px\'></span>Pourtant ce sont nos souffrances,<br><span style=\'padding-left:15px\'></span>Nos souffrances qu’il porta.<br><span style=\'padding-left:15px\'></span>C’est de nos douleurs qu’il s’est chargé<br><span style=\'padding-left:15px\'></span>Et le châtiment qui nous donne la paix<br><span style=\'padding-left:15px\'></span>Oui, qui nous donne la paix,<br><span style=\'padding-left:15px\'></span>Est tombé sur lui. (ter)<br><br>Nous étions tous errants, tous égarés.<br>Chacun de nous suivait sa propre voie.<br>Nous l’avons dédaigné, oui, méprisé<br>Et nous n’avons fait de lui aucun cas.<br><br>Qui a cru qu’il était frappé par Dieu,<br>Meurtri, brisé, blessé pour nos péchés ?<br>Qui a cru, qui a cru que Dieu, sur lui<br>Faisait retomber nos iniquités ?<br>', NULL),
(21, 'Je te célèbre', '21', 'Ps 138', 'Je te célèbre de tout mon cœur, je chante tes louanges<br>Je célèbre ton nom à cause de ta bonté.<br>Le jour où je t’ai invoqué, tu m’as exaucé.<br>Tu m’as rassuré et fortifié.<br>Et dans la détresse, tu me rends la vie,<br>Tu t’élèves contre mes ennemis.<br>L’Éternel agira en ma faveur !<br>Éternel, ta bonté dure toujours !<br>Je te célèbre de tout mon cœur, je chante tes louanges.<br>Je célèbre ton nom, à cause de ta bonté.<br><br>', NULL),
(22, 'Toi, mon ami, fortifie-toi', '22', '2 Tm 2', 'Toi, mon ami, fortifie-toi dans la grâce.<br>Souffre avec moi comme un soldat de Jésus-Christ.<br>Ne t’embarrasse pas des choses de la vie. (bis)<br><br><span style=\'padding-left:15px\'></span>Et ce que tu as entendu, confie-le à des fidèles<br><span style=\'padding-left:15px\'></span>Qui soient capables à leur tour<br><span style=\'padding-left:15px\'></span>De bien l’enseigner à d’autres.<br><br>Comme l’athlète combat suivant les règles,<br>De même que le laboureur doit travailler,<br>Travaille aussi avant de recueillir les fruits (bis)<br><br>Efforce-toi de te montrer au Père<br>Comme un ouvrier n’ayant point à rougir.<br>Dispense la Parole de la vérité. (bis)<br><br>Fuis les passions que connaît la jeunesse.<br>Recherche la douceur et la charité,<br>La paix avec ceux qui invoquent le Seigneur. (bis)<br>', NULL),
(23, 'Je lève les yeux', '23', 'Ps 121', '<span style=\'padding-left:15px\'></span>Je lève les yeux vers les montagnes;<br><span style=\'padding-left:15px\'></span>D’où me viendra le secours ?<br><span style=\'padding-left:15px\'></span>Le secours me vient de l’Éternel<br><span style=\'padding-left:15px\'></span>Qui a fait les cieux et la terre.<br><span style=\'padding-left:15px\'></span>Je lève les yeux vers les montagnes;<br><span style=\'padding-left:15px\'></span>D’où me viendra le secours ?<br><br>Il ne permettra point que ton pied chancelle.<br>Celui qui te garde ne sommeillera pas.<br>Voici, il ne sommeille, ni ne dort<br>Celui qui te garde, ô Israël.<br>', NULL),
(24, 'Si je parlais le plus parfait langage', '24', 'CGG 177;1 Co 13', 'Si je parlais le plus parfait langage,<br>Si même un ange me prêtait le sien,<br>Que me vaudrait ce futile avantage ?<br>Si je n’ai pas l’amour, je ne suis rien !<br>Je ne suis rien qu’un airain qui résonne,<br>Une cymbale au rythme répété.<br>Tout manque encore aux grâces que Dieu donne<br>Si je n’ai pas au cœur l’amour, la charité.<br><br>Et quand j’aurais le don de prophétie,<br>Quand tout secret me serait révélé,<br>Quand j’atteindrais au savoir, au génie,<br>Quand je devrais, martyr, être brûlé,<br>Ou si ma foi transportait la montagne<br>Et ma pitié distribuait mon bien,<br>Quelque mérite en cela que je gagne<br>Sans cet amour, tout ne me servirait de rien.<br><br>La charité se montre patiente<br>Et bienveillante à l’égard du prochain,<br>N’est pas jalouse et non plus ne se vante,<br>Ne s’enfle pas d’orgueil, est sans dédain,<br>Pleine d’égards, ne fait tort à personne,<br>Tout égoïsme est chez elle écarté,<br>Point ne s’irrite et jamais ne soupçonne,<br>Réprouve l’injustice et veut la vérité.<br><br>Que de douceur et de paix elle apporte<br>Car elle excuse tout, elle croit tout !<br>Tout elle espère et tout elle supporte,<br>Mettant son baume et son parfum partout.<br>Les plus beaux dons disparaissent et meurent,<br>Cette vertu vit en éternité.<br>Foi, espérance et charité demeurent,<br>Mais de ces trois, la plus grande est la charité.<br>', NULL),
(25, 'Ne soyez pas surpris', '25', '1 Pi 2;4', 'Ne soyez pas surpris,<br>Comme d’une chose étrange qui vous arrive,<br>De la fournaise qui est au milieu de vous<br>Pour vous éprouver.<br>Mais réjouissez-vous d’avoir part aux souffrances,<br>Aux souffrances de Christ, afin que vous soyez,<br>Vous soyez vous aussi dans la joie<br>Quand sa gloire apparaîtra ! (bis)<br><br>Supportez la souffrance;<br>Quand vous faites le bien, c’est une grâce,<br>Car c’est à cela que vous avez été, été appelés.<br>Christ a souffert pour vous, il porta sur le bois,<br>Nos péchés en son corps, lui qui n’a pas péché,<br>Et par les meurtrissures duquel<br>Vous avez été guéris. (bis)<br><br>Si pour le nom de Christ<br>Vous êtes outragés, vous êtes heureux<br>Parce que l’Esprit de gloire, l’Esprit de Dieu,<br>Repose sur vous.<br>Oui, réjouissez-vous d’avoir part aux souffrances,<br>Aux souffrances de Christ, afin que vous soyez,<br>Vous soyez vous aussi dans la joie<br>Quand sa gloire apparaîtra ! (bis)<br>', NULL),
(26, 'La foi, c’est certitude', '26', 'Hb 11', 'La foi, c’est certitude et ferme assurance<br>Des choses qu’on ne voit pas et qu’on espère.<br>C’est la louange et toute la confiance<br>Avant d’avoir vu l’intervention du Père.<br><br>Sans elle, impossible de vraiment lui plaire<br>Car si nous voulons adorer sa personne<br>Il nous faut croire qu’il vit et rémunère<br>Chacun de ceux qui le cherchent et se donnent.<br><br>La raison pourra trouver inadmissible<br>Que Dieu créa le monde par sa Parole.<br>Nous croyons qu’il fut formé par l’invisible.<br>Dieu confond les sages par les choses folles.<br><br>Avertis des choses sans les voir encore,<br>Et saisis d\'une crainte respectueuse,<br>Entrons dans l\'obéissance qui l\'honore<br>Sans écouter nos pensées tumultueuses.<br>', NULL),
(27, 'Alléluia', '27', 'Lc 1', '<span style=\'padding-left:15px\'></span>Alléluia, alléluia, alléluia ! (bis)<br><span style=\'padding-left:15px\'></span>Un Sauveur nous est donné, alléluia, alléluia !<br><br>Un Sauveur qui nous délivre de la main de nos ennemis,<br>Pour permettre à ses enfants de le servir sans rien craindre,<br>Et de marcher ainsi pour lui en sainteté et justice<br>Les jours de leur vie ici-bas. (bis)<br><br>Un Sauveur qui nous éclaire ainsi que ceux qui sont assis<br>Dans les ténèbres de la nuit et dans les ombres de la mort.<br>Il est venu pour diriger chacun des pas de notre vie<br>Dans le seul chemin de la paix. (bis)<br>', NULL),
(28, 'La trompette sonnera', '28', '1 Co 15;1 Th 4;Ap 7', 'La trompette sonnera, et enfin retentira,<br>Et nous serons changés, enfin, enfin ressuscités.<br>Notre ennemie, la mort sera vaincue, et engloutie dans la victoire<br>Et pour toujours de la gloire céleste nous serons vêtus.<br><br>La trompette sonnera, et enfin retentira,<br>Et le Seigneur viendra du ciel, du ciel il descendra.<br>Sur les nuées nous serons enlevés, transformés à son image.<br>Nous le verrons dans sa magnificence éternellement.<br><br>À Dieu, qui est sur son trône, et au Seigneur Jésus-Christ<br>Soient rendus tout honneur, la gloire, la force et la louange !<br>Devant l’Agneau nous serons jour et nuit dans son temple à son service,<br>Et nous serons conduits par sa présence aux sources de vie.<br>', NULL),
(29, 'Ils erraient dans l’immense désert', '29', 'Ps 107', 'Ils erraient dans l’immense désert, ils marchaient dans la solitude.<br>Ils souffraient de la faim, de la soif, leur âme était bien languissante.<br>Il leur fit suivre le droit chemin, il satisfit leur âme altérée.<br>Il combla de biens l’âme affamée.<br><br>Ceux qui vivaient captifs, enchaînés à cause de leur cœur révolté,<br>Ceux qu’il a brisés par la souffrance à cause de leur cœur méprisant,<br>Il les fit sortir des ténèbres, il rompit leurs chaînes et leurs liens,<br>Il les délivra de leur misère.<br><br>Par leur conduite coupable, ils s’étaient rendus bien malheureux !<br>Ils touchaient aux portes de la mort, refusant toute nourriture.<br>Il leur envoya sa Parole, il mit sa main sur eux, les guérit;<br>Ils furent retirés de la fosse.<br><br>Éperdus en face du danger, saisis de vertige, titubant,<br>Ils chancelaient tous comme un homme ivre, perdant toute leur habileté.<br>Il fit arrêter la tempête, il apporta le calme et la paix,<br>Les conduisant au port désiré.<br><br>Louez l’Éternel car il est bon, car son amour sera éternel !<br>Qu’ainsi disent tous ses rachetés, ceux qu’il délivra de l’ennemi.<br>Dans leur détresse, ils l’invoquèrent; il répondit à leur prière,<br>De leurs angoisses il les délivra.<br>', NULL),
(30, 'Ouvre mes yeux', '30', 'Ps 119', '<span style=\'padding-left:15px\'></span>Ouvre mes yeux pour que je contemple<br><span style=\'padding-left:15px\'></span>Les merveilles de tes ordonnances<br><span style=\'padding-left:15px\'></span>Je t’invoque de tout cœur, Éternel,<br><span style=\'padding-left:15px\'></span>Écoute ma voix selon ta bonté. (bis)<br><br>Ô Dieu, de tout mon cœur je te cherche,<br>Ne me laisse pas égarer loin de toi !<br>Je serre ta Parole dans mon cœur<br>Afin de ne pas pécher contre toi. (bis)<br><br>Ma part est de garder ta Parole.<br>J’éloigne mon pied de tous les mauvais chemins,<br>Ne veux m’écarter de toutes tes lois<br>Car toi seul, Seigneur, tu peux m’enseigner. (bis)<br><br>Ta Parole est une lampe à mes pieds<br>Et une lumière le long de mon sentier.<br>Sa révélation seule nous éclaire,<br>Elle donne aux simples de la science. (bis)<br>', NULL),
(31, 'Ô mon âme', '31', 'Ps 103', '<span style=\'padding-left:15px\'></span>Ô mon âme, oui, je veux bénir l’Éternel,<br><span style=\'padding-left:15px\'></span>Que tout en moi célèbre son saint Nom !<br><span style=\'padding-left:15px\'></span>Ô mon âme, oui, je veux bénir l’Éternel,<br><span style=\'padding-left:15px\'></span>N’oublier aucun de ses bienfaits !<br><br>C’est lui qui pardonne toutes tes iniquités,<br>Qui guérit toutes tes maladies.<br>C’est lui qui délivre ton âme de la mort,<br>Qui te couronne de sa charité.<br><br>C’est lui qui rassasie de bienfaits tes vieux jours,<br>Qui te fait rajeunir comme l’aigle.<br>Comme un père prend compassion de tous ses enfants,<br>L’Éternel bénit tous ceux qui le craignent.<br><br>Il est miséricordieux et compatissant;<br>L’Éternel ne conteste pas sans cesse<br>Mais autant les cieux sont au-dessus de la terre,<br>Autant sa bonté est grande pour nous.<br>', NULL),
(32, 'Va avec la force que tu as', '32', 'Jg 6;Js 1;Jr 1', '<span style=\'padding-left:15px\'></span>Va, va, va, avec la force que tu as.<br><span style=\'padding-left:15px\'></span>Je serai Mmi-même avec toi;<br><span style=\'padding-left:15px\'></span>Fortifie-toi et prends courage !<br><span style=\'padding-left:15px\'></span>(bis)<br><br>Ne dis pas : "Je suis un enfant".<br>Tu iras vers tous ceux que je te montrerai,<br>Et tu diras tout ce que je t’ordonnerai.<br>Voici, je mets mes paroles dans ta bouche.<br>Je veille sur ma Parole pour l’exécuter.<br>', NULL),
(33, 'À force de marcher', '33', 'Es 57', '<span style=\'padding-left:15px\'></span>À force de marcher, tu te fatigues<br><span style=\'padding-left:15px\'></span>Et tu ne dis pas :" j’y renonce !"<br><span style=\'padding-left:15px\'></span>Tu trouves encore de la vigueur dans ta main;<br><span style=\'padding-left:15px\'></span>Aussi n’es-tu pas abattu.<br><br>Et qui redoutais-tu, qui craignais-tu<br>Pour que tu ne te souviennes plus de moi ?<br>Quand tu crieras, qui te délivrera ?<br>Tes œuvres ne te profiteront pas. (bis)<br><br>Mais moi, je suis avec le cœur contrit<br>Afin de ranimer l’esprit brisé.<br>Je ne veux pas contester à toujours<br>Quand les âmes tombent en défaillance. (bis)<br><br>J’ai vu ses voies et je le guérirai.<br>Sur la voie je lui servirai de guide.<br>Je le consolerai et ceux qui pleurent,<br>Je mettrai la louange sur les lèvres. (bis)<br>', NULL),
(34, 'Je répandrai une eau pure', '34', 'Ez 36', '<span style=\'padding-left:15px\'></span>Je répandrai une eau pure, et vous serez purifiés.<br><span style=\'padding-left:15px\'></span>Je laverai vos souillures et briserai vos idoles.<br><span style=\'padding-left:15px\'></span>Je donnerai un cœur nouveau,<br><span style=\'padding-left:15px\'></span>Mettrai en vous l’Esprit nouveau !<br><span style=\'padding-left:15px\'></span>J\'ôterai de votre corps le cœur de pierre<br><span style=\'padding-left:15px\'></span>Pour vous donner un cœur de chair.<br><span style=\'padding-left:15px\'></span>Je mettrai mon Esprit en vous.<br><span style=\'padding-left:15px\'></span>Je ferai que vous suiviez mes ordonnances,<br><span style=\'padding-left:15px\'></span>Et que vous observiez et pratiquiez mes lois.<br><br>Alors vous vous souviendrez de votre conduite coupable,<br>De vos actions qui n’étaient pas bonnes,<br>Vous vous prendrez vous-mêmes en dégoût<br>À cause de vos iniquités.<br>', NULL),
(35, 'Je chante la justice', '35', 'Ps 101', '<span style=\'padding-left:15px\'></span>Je chante la justice et la bonté.<br><span style=\'padding-left:15px\'></span>C\'est à toi, Éternel, que je chante.<br><span style=\'padding-left:15px\'></span>Je prends garde à la voie droite.<br><span style=\'padding-left:15px\'></span>Quand viendras-tu à moi ?<br><br>Je marche dans la vérité de mon cœur<br>Au milieu de ma maison.<br>Je ne mets rien de mauvais devant mes yeux.<br>Je hais la conduite des pécheurs.<br>Je ne veux pas connaître le méchant,<br>Celui qui calomnie son prochain en secret.<br>J\'ai les yeux sur les fidèles du pays<br>Pour qu\'ils demeurent auprès de moi.<br>', NULL),
(36, 'Fais-moi dès le matin', '36', 'Ps 143', '<span style=\'padding-left:15px\'></span>Fais-moi dès le matin entendre ta bonté.<br><span style=\'padding-left:15px\'></span>Fais-moi connaître le chemin où je dois marcher.<br><span style=\'padding-left:15px\'></span>Car je me confie en toi; conduis-moi dans tes voies !<br><br>Éternel, écoute ma prière,<br>Prête l’oreille à mes supplications.<br>L’ennemi poursuit mon âme,<br>Il foule à terre ma vie.<br>J’habite dans les ténèbres<br>Comme ceux qui sont morts depuis longtemps. (bis)<br>', NULL),
(37, 'Les terres d’un homme riche', '37', 'Lc 12;Mt 16', 'Les terres d’un homme riche lui avaient beaucoup rapporté.<br>Il raisonna en lui-même, se disant : "Que ferai-je donc ?<br>Voici : j’abattrai mes greniers et j’en bâtirai de plus grands,<br>J’amasserai ma récolte et j’y poserai tous mes biens.<br>Alors je me dirai : mon âme, réjouis-toi, repose-toi.<br>Tu peux manger, boire et dormir, devant toi s’ouvre cette vie."<br><br><span style=\'padding-left:15px\'></span>Cette nuit-là, Dieu lui parla :"insensé, aujourd’hui-même<br><span style=\'padding-left:15px\'></span>Je rappellerai ton âme, et ce que tu as préparé<br><span style=\'padding-left:15px\'></span>À qui sera-t-il donc donné, à qui sera-t-il donc donné ?"<br><br>Que servirait-il à l’homme de gagner l’or du monde entier,<br>S’il perdait un jour son âme, sa fortune et toute sa gloire ?<br>Ou que pourrait donner cet homme, en échange de cette vie ?<br>N’est-elle pas plus que l’habit, la nourriture et l’argent ?<br>Ne t’amasse pas ces trésors, ceux qui rouillent et qui ternissent,<br>Amasse-les donc dans le ciel, un jour, tu les retrouveras.<br><br><span style=\'padding-left:15px\'></span>Cette nuit, Dieu peut te parler : "Insensé, aujourd’hui-même<br><span style=\'padding-left:15px\'></span>Je puis rappeler ton âme, et ce que tu as préparé<br><span style=\'padding-left:15px\'></span>À qui sera-t-il donc donné, à qui sera-t-il donc donné ?"<br><span style=\'padding-left:15px\'></span><br><span style=\'padding-left:15px\'></span>Coda :<br><span style=\'padding-left:15px\'></span>Il en est ainsi de celui qui amasse pour lui-même,<br><span style=\'padding-left:15px\'></span>Et qui n’est pas riche pour Dieu. (ter)<br>', NULL),
(38, 'Je t\'exalte, ô seigneur', '38', 'Ps 29;30', 'Je T\'exalte, ô Seigneur, car tu m\'as relevé.<br>Oui, j\'ai crié à toi et tu m\'as soulagé.<br>Dans ma sécurité, je crus ne point broncher.<br>Alors je fus troublé.<br>Éternel, j\'ai crié à toi, j\'ai imploré ton nom.<br>Secours-moi, aie pitié de moi !<br><br><span style=\'padding-left:15px\'></span>Tu délias mon sac et me ceignis de joie<br><span style=\'padding-left:15px\'></span>Afin que mon cœur muet te chante.<br><span style=\'padding-left:15px\'></span>Mon Dieu, je te louerai toujours ! (bis)<br><br>L\'Éternel est vivant, il est majestueux,<br>Sa voix brise les cœurs, enfante le bonheur.<br>Il bénit ses enfants et de son bras puissant<br>Il règne sur son trône.<br>Rendez honneur à l\'Éternel ! Oui gloire soit à Dieu !<br>Tous les peuples prosternez-vous !<br>', NULL),
(39, 'Je devance les veilles', '39', 'Ps 119;Hb 6', '<span style=\'padding-left:15px\'></span>Je devance les veilles, j\'ouvre les yeux pour lire ta Parole.<br><span style=\'padding-left:15px\'></span>Je devance l\'aurore, et je crie, j\'espère en tes promesses.<br><br>C\'est par la foi et par la persévérance<br>Que nous hériterons des promesses.<br>Conservons jusqu\'à la fin cette espérance.<br>Ayons du zèle, non de la paresse.<br>', NULL),
(40, 'J\'ai cherché l\'Éternel', '40', 'Ps 34', '<span style=\'padding-left:15px\'></span>J\'ai cherché l\'Éternel, et il m\'a répondu,<br><span style=\'padding-left:15px\'></span>Il m\'a délivré de toutes mes frayeurs.<br><span style=\'padding-left:15px\'></span>J\'ai cherché l\'Éternel, et il m\'a répondu,<br><span style=\'padding-left:15px\'></span>Je le bénirai en tout temps, en tout temps.<br><br>L\'Éternel est près de ceux qui ont le cœur brisé,<br>Et il sauve ceux qui ont un esprit abattu.<br>Et quand les justes crient, l\'Éternel les entend.<br>Ceux qui l\'ont pour refuge échappent au châtiment.<br><br>Recherche et poursuis la paix, éloigne-toi du mal.<br>Cherche en lui ton refuge et tu seras heureux.<br>Et si tu crains l\'Éternel, rien ne te manquera;<br>Au jour de la détresse il te délivrera.<br>', NULL),
(41, 'L\'éternel est ma lumière', '41', 'Ps 25;27;28;30', '<span style=\'padding-left:15px\'></span>L\'Éternel est ma lumière, de qui aurais-je crainte ?<br><span style=\'padding-left:15px\'></span>L\'Éternel est mon salut, de qui aurais-je peur ?<br><br>Il voit ma misère et ma peine, et il pardonne tous mes péchés.<br>II m\'a guéri, m\'a relevé, m\'a affermi, m\'a ceint de joie.<br><br>II enseigne aux humbles la voie, espère en lui, fortifie-toi !<br>En mon Dieu mon cœur se confie, et en lui je suis secouru.<br><br>Ô Dieu, j\'élève à toi mon âme, conduis-moi dans ta vérité !<br>Et enseigne-moi tes sentiers ! Je mets en toi mon espérance.<br>', NULL),
(42, 'Je reconnais que tu peux tout', '42', 'Jb 42', 'Je reconnais que tu peux tout, rien ne s\'oppose à tes pensées.<br>Quel est celui qui a la folie d\'obscurcir mes desseins ?<br>Oui, j\'ai parlé, sans les comprendre<br>De merveilles qui me dépassent.<br>Oui, j\'ai parlé, sans les comprendre<br>De merveilles que je ne conçois pas.<br><br>Écoute-moi, et je parlerai,<br>Je t\'interrogerai, tu m\'instruiras.<br>(bis)<br><br>Mon oreille avait entendu parler de toi.<br>Mais maintenant mon œil t\'a vu, (bis)<br>C\'est pourquoi je me repens. (bis)<br>', NULL),
(43, 'Oui, c\'est par grâce', '43', 'Ep 2', '<span style=\'padding-left:15px\'></span>Oui, c\'est par grâce que je suis sauvé (bis)<br><span style=\'padding-left:15px\'></span>Par le moyen de la foi.<br><span style=\'padding-left:15px\'></span>Oui, c\'est par grâce que je suis sauvé.<br><br>Cela ne vient pas de moi,<br>C\'est le don de Dieu,<br>C\'est le don de Dieu<br>(bis)<br><br>Dieu conduit dans les œuvres<br>Déjà préparées,<br>Déjà préparées.<br>(bis)<br>', NULL),
(44, 'N\'oublie pas', '44', 'Hb 12;Lm 3', '<span style=\'padding-left:15px\'></span>N\'oublie pas, n\'oublie pas<br><span style=\'padding-left:15px\'></span>Que Dieu t\'aime comme un fils.<br><span style=\'padding-left:15px\'></span>N\'oublie pas, n\'oublie pas<br><span style=\'padding-left:15px\'></span>Que Dieu t\'aime et te châtie.<br><br>Mon fils ne méprise pas, (non mais crois)<br>Supporte le châtiment, (non mais crois)<br>Ne te décourage pas (non mais crois)<br>Quand ton père te reprend.<br><br>Dieu te traite comme un fils, (oh! oui crois)<br>Il te châtie pour ton bien. (oh! oui crois)<br>Il veut te donner la vie, (oh! oui crois)<br>Confie-toi et ne crains rien.<br><br>Tu te tiendras silencieux, (oh! oui crois)<br>Solitaire puisqu\'il le veut, (oh! oui crois)<br>La bouche dans la poussière (oh! oui crois)<br>Sans perdre toute espérance.<br><br>Fortifie donc tes mains (oh! oui crois)<br>Et tes genoux affaiblis. (oh! oui crois)<br>Recherche ce qui est saint (oh! oui crois)<br>Pour que tu sois affermi.<br><br><span style=\'padding-left:15px\'></span>Oh, oui crois ! Oh, oui crois<br><span style=\'padding-left:15px\'></span>Que Dieu t\'aime comme un fils.<br><span style=\'padding-left:15px\'></span>Oh, oui crois ! Oh, oui crois<br><span style=\'padding-left:15px\'></span>Que Dieu t\'aime et te châtie.<br>', NULL),
(45, 'Comme Christ ressuscité', '45', 'Rm 6', 'Comme Christ ressuscité, de même nous aussi<br>Marchons donc par la foi, sachant que l\'homme ancien<br>A été crucifié, le corps du mal détruit.<br>Ne soyons plus esclaves du péché !<br><br>Regardons-nous comme morts, mais vivants pour Jésus.<br>Le péché n\'aura plus de pouvoir sur nous tous.<br>Nous avons obéi, de cœur été instruits.<br>Livrons notre vie entière à Jésus !<br>', NULL),
(46, 'La loi de l’Éternel', '46', 'Ps 19', '<span style=\'padding-left:15px\'></span>La loi de l’Éternel est parfaite, elle restaure l’âme.<br><span style=\'padding-left:15px\'></span>Les ordonnances de Dieu sont droites.<br><span style=\'padding-left:15px\'></span>Son témoignage est véritable, il rend sage l’ignorant,<br><span style=\'padding-left:15px\'></span>Ses commandements éclairent les yeux.<br><br>La crainte de Dieu est pure, elle subsiste à toujours.<br>Les jugements de Dieu sont vrais, justes éternellement.<br>Ils sont bien plus précieux que l’or,<br>Plus doux que le miel des rayons.<br>Ils sont bien plus précieux que l’or,<br>Plus doux que le miel des rayons.<br><br>Ton serviteur aussi reçoit toutes les instructions<br>La récompense est grande pour ceux qui les observent<br>Qui connaît ses égarements ?<br>Pardonne-moi ceux que j’ignore.<br>Qui connaît ses égarements ?<br>Pardonne-moi ceux que j’ignore.<br>', NULL),
(47, 'Revenez de vos mauvaises voies', '47', 'Ez 18;33;Ps 53;Rm 3;Ga 2;3', '<span style=\'padding-left:15px\'></span>Revenez de vos mauvaises voies,<br><span style=\'padding-left:15px\'></span>Pourquoi donc mourriez-vous ?<br><span style=\'padding-left:15px\'></span>(bis)<br><br>L\'insensé dit en son cœur : "Il n\'y a point de Dieu"<br>Et il s\'est tant corrompu parmi les pécheurs<br>Qu\'il ne peut faire le bien qu\'il voudrait.<br>Du haut des cieux Dieu regarde : "Qui donc me cherche ?<br>Pas un seul ne fait le bien, tous sont égarés,<br>Pas un seul ne fait le bien, tous sont pervertis."<br><br>"Ce que je désire, dit Dieu, c\'est un changement.<br>Change ta conduite et vis, laisse le péché !<br>Oui, que le méchant revienne de son mal !<br>Détournez-vous de vos transgressions, changez de voie !<br>Faites-vous un cœur nouveau, un esprit nouveau;<br>Faites-vous un cœur nouveau par notre Sauveur !"<br><br>Nous sommes tous des coupables, dit la loi de Dieu.<br>Aucun par ses œuvres ne sera justifié<br>Car la vraie justice nous est donnée.<br>Par Jésus-Christ crucifié au bois, pour ceux qui croient.<br>Afin que quiconque croit ne périsse pas<br>Mais qu\'il ait toujours la vie, la vie éternelle.<br><br><span style=\'padding-left:15px\'></span>Oh ! Venez, revenez à Jésus,<br><span style=\'padding-left:15px\'></span>Il a tout accompli !<br><span style=\'padding-left:15px\'></span>(bis)<br>', NULL),
(48, 'Mon dieu à toi j\'élève mon âme', '48', 'Ps 25', '<span style=\'padding-left:15px\'></span>Mon Dieu à toi j\'élève mon âme.<br><span style=\'padding-left:15px\'></span>Éternel, en toi je me confie.<br><span style=\'padding-left:15px\'></span>Que je ne sois pas couvert de honte<br><span style=\'padding-left:15px\'></span>Puisque tu es le Dieu de mon salut !<br><br>Les sentiers de l\'Éternel sont faits de miséricorde<br>Pour ceux qui gardent sa loi, ses commandements.<br>Il pardonne l\'iniquité, efface nos transgressions.<br>Il montre aux pécheurs la voie et la justice.<br><br>Celui qui craint l\'Éternel, Dieu lui montre le chemin<br>Et son âme reposera, remplie de bonheur.<br>Des angoisses de son âme et des chagrins de son cœur,<br>Dieu délivre des détresses pour toujours.<br>', NULL),
(49, 'C\'est donc en vain qu\'ils le prient', '49', 'Es 59;1', '<span style=\'padding-left:15px\'></span>C\'est donc en vain qu\'ils le prient<br><span style=\'padding-left:15px\'></span>En élevant vers lui leurs mains.<br><span style=\'padding-left:15px\'></span>C\'est donc en vain qu\'ils le prient,<br><span style=\'padding-left:15px\'></span>Le ciel leur semble être d\'airain.<br><br>Non, sa main n\'est pas trop courte,<br>Son oreille n\'est pas trop sourde,<br>Pour vous entendre et vous écouter,<br>Pour vous atteindre et vous sauver.<br><br>Mais ce sont là tous vos crimes<br>Qui le blessent et qui le briment.<br>Vos péchés vous cachent sa face.<br>De vous écouter, il se lasse.<br><br><span style=\'padding-left:15px\'></span>Coda :<br><span style=\'padding-left:15px\'></span>Quand vous étendez vos mains<br><span style=\'padding-left:15px\'></span>Je détourne de vous mes yeux.<br><span style=\'padding-left:15px\'></span>Quand vous multipliez vos prières<br><span style=\'padding-left:15px\'></span>Je n\'écoute pas.<br><span style=\'padding-left:15px\'></span>Venez et plaidons, nous dit Dieu<br><span style=\'padding-left:15px\'></span>Lavez-vous, purifiez-vous !<br><span style=\'padding-left:15px\'></span>Si vos péchés sont comme le cramoisi,<br><span style=\'padding-left:15px\'></span>Ils deviendront blancs comme la neige, comme la neige.<br>', NULL),
(50, 'Heureux l\'homme qui place', '50', 'Ps 40', '<span style=\'padding-left:15px\'></span>Heureux l\'homme qui place en l\'Éternel sa confiance,<br><span style=\'padding-left:15px\'></span>Que tous ceux qui le craignent soient dans l\'allégresse<br><span style=\'padding-left:15px\'></span>Et se réjouissent en lui !<br><span style=\'padding-left:15px\'></span>Heureux l\'homme qui place en l\'Éternel sa confiance !<br><span style=\'padding-left:15px\'></span>Que tous ceux qui aiment son salut<br><span style=\'padding-left:15px\'></span>Disent sans cesse : "Exalté soit l\'Éternel, exalté soit l\'Éternel !"<br><br>J\'avais mis en l\'Éternel mon espérance.<br>Il s\'est incliné vers moi, il a écouté mes cris,<br>Il m\'a retiré du fond de la boue<br>Et il a dressé mes pas sur le roc.<br>Il a mis dans ma bouche un cantique nouveau,<br>Une louange à notre Dieu.<br>Oui, il a dressé mes pas sur le roc.<br>Beaucoup l\'ont vu, et ont eu de la crainte,<br>Et ils se sont confiés en l\'Éternel. (bis)<br><br>Il ne veut ni sacrifice ni offrande.<br>Je suis pauvre et indigent, mais le Seigneur pense à moi,<br>Il est mon aide et mon libérateur.<br>Je veux faire ta volonté, mon Dieu !<br>Je ne cache pas ta bonté et ta fidélité.<br>Ta loi est au fond de mon cœur.<br>Je publie ta vérité et ton salut,<br>Tes merveilles et tes desseins en notre faveur.<br>Ne me refuse pas tes compassions ! (bis)<br><br>', NULL),
(51, 'Souviens-toi', '51', 'Ec 12', '<span style=\'padding-left:15px\'></span>Souviens-toi, souviens-toi de ton Créateur !<br><span style=\'padding-left:15px\'></span>Souviens-toi de ton Créateur pendant les jours de ta jeunesse,<br><span style=\'padding-left:15px\'></span>Avant que la poussière retourne à la terre comme elle y était.<br><span style=\'padding-left:15px\'></span>Souviens-toi, souviens-toi de ton Créateur !<br><span style=\'padding-left:15px\'></span>Souviens-toi de ton Créateur !<br><span style=\'padding-left:15px\'></span>Avant que l\'esprit ne retourne à Dieu qui l\'a donné.<br><br>Réjouis-toi, réjouis-toi et marche dans les voies de ton cœur !<br>Réjouis-toi, réjouis-toi, va selon les regards de tes yeux !<br>Mais sache, mais sache que Dieu te jugera. (bis)<br>', NULL),
(52, 'Si quelqu\'un est en christ', '52', '2 Co 5;Cl 1', '<span style=\'padding-left:15px\'></span>Si quelqu\'un est en Christ<br><span style=\'padding-left:15px\'></span>Il est une nouvelle création.<br><span style=\'padding-left:15px\'></span>Les choses anciennes sont passées.<br><span style=\'padding-left:15px\'></span>Toutes choses sont devenues nouvelles.<br><br>Car Dieu était en Christ<br>Pour réconcilier le monde en offrant sa vie.<br>Nous qui étions ennemis de Dieu<br>Il nous a réconciliés.<br><br>Christ était sans péché.<br>Il devint péché pour nous, oui, à cause de nous !<br>Pour nous faire paraître devant lui<br>Justes, saints et pardonnés.<br><br>Tout cela vient de Dieu<br>Qui nous a réconciliés avec lui par Christ.<br>Qui nous a donné le ministère<br>De la réconciliation.<br>Qui nous a donné le ministère<br>De la réconciliation.<br>', NULL),
(53, 'Éternel, tu me feras connaitre', '53', 'Ps 16', '<span style=\'padding-left:15px\'></span>Éternel, tu me feras connaître le sentier de la vie,<br><span style=\'padding-left:15px\'></span>De la vie, de la vie.<br><span style=\'padding-left:15px\'></span>Devant toi la joie abonde,<br><span style=\'padding-left:15px\'></span>La joie abonde toujours.<br><br>Garde-moi, garde-moi, ô Dieu !<br>Car en toi je cherche un refuge.<br>Tu es mon Seigneur, mon souverain bien.<br>Avec toi je ne craindrai rien.<br><br>Je bénis, bénis l\'Éternel.<br>Même dans la nuit mon cœur m\'exhorte.<br>J\'ai l\'Éternel toujours devant les yeux.<br>L\'Éternel est mon conseiller.<br><br>Jamais je ne chancellerai<br>Car l\'Éternel est à ma droite.<br>Ainsi mon esprit est dans l\'allégresse,<br>Et tout mon cœur est dans la joie.<br>', NULL),
(54, 'Venez à moi', '54', 'Mt 11', '<span style=\'padding-left:15px\'></span>Venez à moi, vous qui êtes fatigués !<br><span style=\'padding-left:15px\'></span>Venez à moi, vous tous qui êtes chargés !<br><span style=\'padding-left:15px\'></span>Venez à moi, vous qui portez le joug,<br><span style=\'padding-left:15px\'></span>Le joug de la détresse, le joug de la mort !<br><span style=\'padding-left:15px\'></span>Venez à moi, vous qui traînez vos chaînes,<br><span style=\'padding-left:15px\'></span>Les chaînes du doute, les chaînes de l\'angoisse.<br><br><span style=\'padding-left:15px\'></span>Fin : "Venez à moi", nous dit Jésus. (bis)<br><br>"Venez à moi, nous dit Jésus, <br>Et je vous donnerai du repos,<br>(bis)<br>Du repos pour vos cœurs meurtris,<br>Repos pour vos âmes lassées."<br><br>Prenez mon joug, car il est doux.<br>Recevez toutes mes instructions.<br>(bis)<br>Mon fardeau est doux et léger.<br>Je suis doux et humble de cœur.<br>', NULL),
(55, 'À celui qui offre', '55', 'Ps 50', '<span style=\'padding-left:15px\'></span>À celui qui offre pour sacrifice<br><span style=\'padding-left:15px\'></span>Des actions de louange à son Dieu,<br><span style=\'padding-left:15px\'></span>Et qui veille sur sa voie<br><span style=\'padding-left:15px\'></span>Je ferai voir le salut de Dieu. (bis)<br><br>Au jour de la détresse invoque-moi;<br>Je te délivrerai, tu me glorifieras.<br>(bis)<br><br>Dieu, l’Éternel, nous parle : Rassemblez-vous !<br>Au nom du sacrifice qui nous a réunis.<br>(bis)<br>', NULL),
(56, 'Je vous ai aimés', '56', 'Ml', '"Je vous ai aimés", dit l’Éternel.<br>Vous dites : "En quoi nous as-tu aimés ?"<br>Un fils honore son père et vous êtes rebelles.<br>Où est la crainte de mon nom car vous me profanez ?<br>Un fils honore son père et vous êtes rebelles.<br>Où est la crainte de mon nom car vous me profanez ?<br><br><span style=\'padding-left:15px\'></span>Prions Dieu maintenant pour qu\'il ait pitié de nous !<br><span style=\'padding-left:15px\'></span>À nous cet ordre maintenant de donner gloire à son saint nom !<br><br>Revenez à moi, dit l’Éternel.<br>Vous dites : En quoi faut-il revenir ?<br>Voici vous me trompez, moi qui suis l’Éternel.<br>Livrez avec joie vos trésors, je veux tous vous bénir.<br>Voici vous me trompez, moi qui suis l’Éternel.<br>Livrez avec joie vos trésors, je veux tous vous bénir.<br><br>Ils seront à moi, dit l’Éternel,<br>Tous ceux qui craignent et honorent mon nom.<br>Tous ceux qui sont à moi verront ma compassion.<br>Ils connaîtront ma justice et ma pleine guérison.<br>Tous ceux qui sont à moi verront ma compassion.<br>Ils connaîtront ma justice et ma pleine guérison.<br>', NULL),
(57, 'Jésus-christ est la lumière', '57', 'Jn 8', 'Jésus-Christ est la lumière du monde;<br>Celui qui le suit ne marchera pas dans les ténèbres.<br>Oh, oh...<br><br>Mais il aura la lumière de la vie;<br>Il ne craindra plus la mort, mais il vivra avec Jésus.<br>Oh, oh...<br><br>Seigneur, tu es la lumière de nos vies.<br>Nous Te bénissons, nous t\'adorons, Seigneur, notre Sauveur !<br>Oh, oh...<br><br>Tu as donné la lumière dans ce monde.<br>Tu es mort sur la croix en versant ton sang pour nos péchés.<br>Oh, oh...<br>', NULL),
(58, 'Heureux l\'homme qui ne marche pas', '58', 'Ps 1', 'Heureux l\'homme qui ne marche pas<br>Selon le conseil des méchants,<br>Qui ne s\'arrête pas sur la voie des pécheurs,<br>Ni en compagnie des moqueurs,<br>Mais qui trouve son plaisir dans la loi de l\'Éternel<br>Et qui la médite jour et nuit.<br>Il est comme un arbre près des eaux<br>Qui donne son fruit en sa saison,<br>Dont le feuillage ne se flétrit pas;<br>Tout ce qu\'il fait lui réussit.<br><br>Il n\'en est pas ainsi des méchants;<br>Comme la paille dissipée au vent.<br>Ils ne résistent pas au jour du jugement,<br>Ni les pécheurs parmi les justes.<br>Mais le Seigneur est avec ceux qui aiment sa loi<br>Et qui la méditent jour et nuit.<br>La voie des pécheurs mène à la ruine<br>Mais le Seigneur connaît leur voie.<br>Il connaît aussi la voie du juste<br>Et il bénit tout ce qu\'il fait.<br>', NULL),
(59, 'Revenez enfants rebelles', '59', 'Jr 3', 'Revenez enfants rebelles,<br>Mon regard ne sera pas sévère.<br>Revenez enfants rebelles,<br>Car je suis miséricordieux.<br>Oui, nous avons péché contre l\'Éternel, (bis)<br>Contre l\'Éternel !<br><br>Revenez enfants rebelles,<br>Reconnaissez vos iniquités<br>Et ne suivez plus les penchants,<br>Les penchants de votre mauvais cœur.<br>Oui, nous avons péché contre l\'Éternel.<br>Nous n\'avons pas écouté, écouté sa voix,<br>Écouté sa voix !<br><br>Revenez enfants rebelles,<br>Je pardonnerai vos infidélités.<br>Ma colère ne dure pas toujours<br>Car je suis, car je suis votre Maître.<br>Oui, nous voici Seigneur, nous allons à toi,<br>Car tu es l\'Éternel, l\'Éternel notre Dieu,<br>L\'Éternel notre Dieu (bis)<br>', NULL);
INSERT INTO `hymn` (`id`, `title`, `num`, `ref`, `lyrics`, `musical_part_id`) VALUES
(60, 'La bienveillance de l’Éternel remplit la terre', '60', 'Ps 33', 'La bienveillance de l\'Éternel remplit la terre.<br>Les cieux ont été faits par sa sainte Parole.<br>Il dit et la chose arrive ! il ordonne et elle existe !<br><br><span style=\'padding-left:15px\'></span>Notre âme espère en l\'Éternel,<br><span style=\'padding-left:15px\'></span>(Notre cœur met en lui sa joie, car il est notre bouclier)<br><span style=\'padding-left:15px\'></span>Il est notre Rocher suprême.<br><span style=\'padding-left:15px\'></span>(Notre âme espère en l\'Éternel, il est notre rocher)<br><br>Heureux celui que Dieu choisit pour héritier !<br>L\'Éternel regarde du haut des cieux les hommes,<br>Il observe tous les habitants, lui qui leur forme le cœur à tous.<br><br>L\'œil de l\'Éternel est sur tous ceux qui Le craignent<br>Afin d\'arracher quelques-uns d\'eux à la mort<br>Et de les faire survivre pendant la grande famine.<br>', NULL),
(61, 'Et l\'Ésprit et l\'Épouse', '61', 'Ap 22', '<span style=\'padding-left:15px\'></span>Et l\'Esprit et l\'Épouse disent : "Viens Seigneur !"<br><span style=\'padding-left:15px\'></span>(Reviens, Seigneur !)<br><span style=\'padding-left:15px\'></span>Que tous ceux qui entendent disent : "Viens bientôt !"<br><span style=\'padding-left:15px\'></span>(Reviens bientôt !)<br><span style=\'padding-left:15px\'></span>Tenons pour certaine sa venue prochaine !<br><span style=\'padding-left:15px\'></span>(Reviens, Seigneur !)<br><span style=\'padding-left:15px\'></span>Parole prophétique, lumière dans la nuit.<br><span style=\'padding-left:15px\'></span>(Reviens bientôt !)<br><br>Prenez donc garde à vous-mêmes<br>De crainte que vos cœurs ne s\'endorment<br>Par les soucis du manger et du boire !<br><br>Ne dormons pas comme les autres;<br>Soyons sobres, veillons !<br>Car vous le savez bien vous-même qu\'il viendra dans la nuit...<br><br>Pour avoir de l\'assurance<br>Demeurez donc en lui,<br>Afin que, lorsqu\'il paraîtra, vous ne soyez confus !<br><br>Ayez entière espérance<br>Dans la grâce de Dieu<br>Qui vous sera manifestée quand Jésus reviendra.<br>', NULL),
(62, 'Je vous laisse la paix', '62', 'Jn 14;Ph 4;1 Pi 5', '<span style=\'padding-left:15px\'></span>Je vous laisse la paix,<br><span style=\'padding-left:15px\'></span>Je vous donne ma paix.<br><span style=\'padding-left:15px\'></span>Je ne la donne pas comme le monde la donne !<br><span style=\'padding-left:15px\'></span>Que votre cœur ne se trouble pas,<br><span style=\'padding-left:15px\'></span>Que votre cœur ne s’alarme pas,<br><span style=\'padding-left:15px\'></span>Croyez en Dieu ! Croyez en Moi !<br><br>Ne vous inquiétez de rien.<br>Faites connaître vos besoins.<br>Par des prières à Dieu. Et la paix de Dieu<br>Gardera vos cœurs, vos pensées en Christ. (bis)<br><br>Dieu résiste aux orgueilleux.<br>Humiliez-vous sous sa main,<br>Et déchargez-vous sur lui de tous vos soucis,<br>Car Dieu lui-même prendra soin de vous. (bis)<br>', NULL),
(63, 'Que Dieu ait pitié de nous', '63', 'Ps 67', 'Que Dieu ait pitié de nous et que Dieu nous bénisse.<br>Qu\'il fasse luire sa face, afin que sur la terre<br>Nous connaissions sa voie, les nations son salut !<br><br><span style=\'padding-left:15px\'></span>Les nations Te louent, ô Dieu, les peuples t\'adorent. (bis)<br><br>Les nations se réjouissent et sont dans l\'allégresse<br>Car tu juges les peuples, tu juges avec droiture.<br>Tu conduis les nations, toute la terre te craint.<br>', NULL),
(64, 'Cherchez l\'Éternel', '64', 'Es 55', 'Cherchez l\'Éternel pendant qu\'il se trouve,<br>Et invoquez-le tandis qu\'il est près !<br>Que le méchant abandonne sa voie<br>Et l\'homme d\'iniquité ses pensées !<br>Car vos pensées ne sont pas mes pensées.<br>Vos voies ne sont pas celles du Seigneur.<br>Mais si vous retournez à l\'Éternel,<br>Notre Dieu aura pitié de vous.<br><br>Comme la pluie ou la neige en hiver<br>Descend des cieux et n\'y retourne pas<br>Sans avoir arrosé, fécondé la terre,<br>Donné de la semence au semeur,<br>Il en est ainsi de toute ma Parole;<br>Elle ne reviendra pas à moi sans effet,<br>Sans avoir exécuté ma volonté<br>Et avoir accompli mes desseins.<br><br>Vous sortirez le cœur rempli de joie,<br>Serez conduits sur des chemins de paix.<br>Les montagnes éclateront d\'allégresse<br>Et tous les arbres battront des mains.<br>Au lieu de l\'épine s\'élèvera le cyprès,<br>Au lieu de la ronce le myrte grandira.<br>Oui, cherchez l\'Éternel pendant qu\'il se trouve !<br>Invoquez-le tandis qu\'il est près ! (bis)<br>', NULL),
(65, 'Il est beau de louer', '65', 'Ps 92', '<span style=\'padding-left:15px\'></span>Il est beau de louer, de célébrer l\'Éternel,<br><span style=\'padding-left:15px\'></span>D\'annoncer le matin ta bonté.<br><span style=\'padding-left:15px\'></span>Tu me réjouis par tes œuvres, ô Éternel !<br><span style=\'padding-left:15px\'></span>Je chante avec allégresse l\'ouvrage de Tes mains.<br><br>Que tes œuvres sont grandes et tes pensées profondes.<br>L\'homme stupide n\'y connaît rien, l\'insensé n\'y prend point garde.<br>Si les méchants croissent comme l\'herbe et ceux qui font le mal fleurissent<br>C\'est pour être anéantis. Mais Toi, tu es le Très-Haut.<br><br>Plantés dans la maison de Dieu, les justes, comme le palmier,<br>Croissent dans les parvis de Dieu, verdoyants, sont pleins de sève,<br>Et dans leur vieillesse portent des fruits. Ils s\'élèvent comme le cèdre.<br>C\'est pour glorifier leur Dieu. L\'Éternel est leur rocher.<br>', NULL),
(66, 'Heureux les affligés', '66', 'Mt 5', 'Heureux les affligés; ils seront consolés,<br>Les pauvres en esprit; le royaume est à eux.<br>Heureux les débonnaires; ils hériteront la terre.<br>Heureux ceux qui ont faim et soif de la justice;<br>Ils seront rassasiés !<br><br>Heureux ceux qui procurent la vraie paix autour d\'eux;.<br>Ils seront appelés fils de notre Seigneur.<br>Auront miséricorde les miséricordieux<br>Heureux tous les cœurs purs car ils verront leur Dieu.<br>Soyez dans l\'allégresse !<br><br>Heureux les méprisés; le ciel leur appartient !<br>Et si l\'on dit du mal sur vous à cause de Dieu,<br>Soyez tous dans la joie et réjouissez-vous.<br>Car votre récompense sera grande dans le ciel.<br>Soyez tous dans la joie !<br><br>Les prophètes avant vous aussi furent outragés.<br>Si le sel de la terre et la lumière du monde<br>Venaient à disparaître pour l\'humanité,<br>Que vos œuvres soient vues pour glorifier le Père !<br>Oui, réjouissez-vous !<br>', NULL),
(67, 'Vous avez été rachetés', '67', '1 Co 6', 'Vous avez été rachetés à un grand prix.<br>Vous avez été rachetés à un grand prix.<br>Au nom du Seigneur Jésus, vous avez été lavés,<br>Sanctifiés, justifiés, justifiés.<br>Glorifiez donc Dieu dans vos corps et votre esprit.<br>Tous ceux qui s\'attachent au Seigneur sont un en lui.<br>Nos corps sont membres de Christ, car tout appartient à Dieu.<br>Ne devenez pas esclaves des hommes !<br><br>Pour nous, il n\'y a qu\'un seul Dieu, un seul Seigneur<br>Qui a créé tout ce qui est, par qui nous sommes.<br>Qu\'as-tu que tu n\'aies reçu, de quoi te glorifies-tu<br>Puisqu\'il nous a tirés de la poussière ?<br>Et pourtant l\'Esprit du Seigneur habite en nous;<br>Nous ne nous appartenons plus, plus à nous-mêmes<br>Soyons fermes dans la foi ! Faisons tout avec amour !<br>Rendons grâces en toutes choses au Seigneur ! (bis)<br>', NULL),
(68, 'Si tu donnes de ta subsistance', '68', 'Es 58', '<span style=\'padding-left:15px\'></span>Si tu donnes de ta subsistance<br><span style=\'padding-left:15px\'></span>À celui qui meurt de faim,<br><span style=\'padding-left:15px\'></span>Si tu rassasies l\'âme indigente,<br><span style=\'padding-left:15px\'></span>Ta lumière se lèvera.<br><span style=\'padding-left:15px\'></span>L\'Éternel sera toujours ton guide.<br><span style=\'padding-left:15px\'></span>Il rassasiera ton âme aride,<br><span style=\'padding-left:15px\'></span>Ta source sera intarissable.<br><br>Donne ton pain à celui qui a faim !<br>Reçois dans ta maison les malheureux !<br>Si tu vois un homme nu, couvre-le;<br>Ne te détourne pas de ton prochain !<br><br>Dénoue les liens de la méchanceté !<br>Brise les chaînes de la servitude !<br>Renvoie libres ceux qui sont opprimés;<br>Éloigne-toi des gestes menaçants !<br><br>Ta lumière poindra comme l\'aurore !<br>Ta guérison germera promptement !<br>Ta justice marchera devant toi,<br>La splendeur de Dieu t\'accompagnera.<br>', NULL),
(69, 'Avec quoi irai-je ?', '69', 'Mi 6;Ps 51', 'Avec quoi irai-je devant l\'Éternel,<br>Et m\'inclinerai-je devant le Très-Haut ?<br>Me prosternerai-je avec des offrandes ?<br>Donnerai-je pour mon crime un premier-né ? (bis)<br><br><span style=\'padding-left:15px\'></span>On t\'a fait connaître, ô homme, ce qui est bien.<br><span style=\'padding-left:15px\'></span>Ce que l\'Éternel demande de toi,<br><span style=\'padding-left:15px\'></span>C\'est que tu pratiques la justice,<br><span style=\'padding-left:15px\'></span>Que tu aimes la miséricorde.<br><span style=\'padding-left:15px\'></span>Avec ton Dieu, marche humblement !<br><br>Tu ne prends pas plaisir aux grands sacrifices.<br>Tu n\'agrées d\'holocaustes pour pardonner.<br>Le sacrifice à Dieu : c\'est l\'esprit brisé.<br>Ne dédaigne pas, Seigneur, un cœur contrit ! (bis)<br>', NULL),
(70, 'Ne crains pas (canon)', '70', 'Es 43', 'A. Ne crains pas, ne crains pas,<br>B. Je t\'ai racheté !<br>C. Ne crains pas, ne crains pas,<br>D. Je ne t\'abandonnerai pas !<br>', NULL),
(71, 'Invoque-moi', '71', 'Ps 91;92', 'Invoque-moi et je te répondrai.<br>Puisque tu m\'aimes, je te délivrerai.<br>Je te protégerai, puisque tu connais mon nom !<br>Et je te ferai voir, je te ferai voir mon salut !<br>Invoque-moi et je te répondrai.<br>Puisque tu m\'aimes, je te délivrerai,<br>Je te délivrerai et tu Me glorifieras.<br>Oh, si tu m\'écoutais, ton bonheur durerait toujours !<br><br><span style=\'padding-left:15px\'></span>Il est beau de louer l\'Éternel,<br><span style=\'padding-left:15px\'></span>D\'annoncer le matin sa bonté,<br><span style=\'padding-left:15px\'></span>Sa fidélité pendant les nuits, pendant les nuits !<br><span style=\'padding-left:15px\'></span>Je chanterai tant que je vivrai<br><span style=\'padding-left:15px\'></span>La bonté, l\'amour de l\'Éternel !<br><span style=\'padding-left:15px\'></span>Je célébrerai sa sainteté, sa sainteté !<br><br>Enseigne-moi tes voies, ô Éternel;<br>Je marcherai dans ta fidélité,<br>Et dispose mon cœur à la crainte de ton nom !<br>Je me confie en toi. En toi, mon Dieu, je ne crains rien.<br>Je ne crains pas les terreurs de la nuit.<br>Aucun fléau n\'approchera de moi<br>Car tu es mon secours, mon refuge chaque jour !<br>Car tu es mon secours et mon refuge chaque jour !<br>', NULL),
(72, 'Vous serez mes témoins', '72', 'Ac 1', 'Vous serez mes témoins, a dit Jésus. (bis)<br>Vous recevrez une puissance, le Saint-Esprit. (bis)<br>Merci Seigneur, car j\'étais perdu.<br>Pour toi je veux vivre maintenant;<br>Prends ma vie, Seigneur, oui prends-la ! (bis)<br><br>Vous serez mes témoins, a dit Jésus. (bis)<br>Et jusqu\'au bout du monde vous parlerez de moi. (bis)<br>Oui, je veux dire au monde entier<br>Que tu m\'as sauvé, m\'as racheté.<br>Envoie-moi, Seigneur, envoie-moi ! (bis)<br><br>Nous sommes ses témoins, a dit Jésus. (bis)<br>Et nous chantons au monde entier : Jésus est le Roi ! (bis)<br>Il est le Sauveur et le Seigneur !<br>Il a donné sa vie sur la croix.<br>Tu peux l\'accepter, viens à lui ! (bis)<br>', NULL),
(73, 'Louez l’éternel, il est bon', '73', 'Ps 66', '<span style=\'padding-left:15px\'></span>Louez l’Éternel ! Il est bon.<br><span style=\'padding-left:15px\'></span>Chantez la gloire de son nom !<br><span style=\'padding-left:15px\'></span>Célébrez-le par vos louanges !<br><span style=\'padding-left:15px\'></span>Dites : "Ô Dieu, tes œuvres sont grandes !"<br><br>La terre se prosterne et chante en ton nom,<br>Chante en ton honneur, ta force et ta gloire.<br><br>Venez, contemplez les œuvres de Dieu;<br>Il est redoutable dans sa majesté.<br>', NULL),
(74, 'Poussez vers le Seigneur', '74', 'Ps 100', 'Poussez vers le Seigneur des cris de joie, (bis)<br>Vous tous, habitants de la terre !<br>Servez le Seigneur avec joie,<br>Venez avec allégresse en sa présence !<br>Sachez que le Seigneur est Dieu !<br>C’est lui qui nous a faits et nous lui appartenons.<br>Nous sommes son peuple et le troupeau de son pâturage.<br>Oh, oh...<br>Entrez dans ses portes avec des louanges, (bis)<br>Dans ses parvis avec des cantiques !<br>Célébrez-le, bénissez son nom !<br>Car le Seigneur est bon, sa bonté dure toujours<br>Et sa fidélité de génération en génération.<br>Car le Seigneur est bon, sa bonté dure toujours<br>Et sa fidélité de génération en génération.<br><br>', NULL);

-- --------------------------------------------------------

--
-- Structure de la table `musical_part`
--

CREATE TABLE `musical_part` (
  `id` int(11) NOT NULL,
  `xml` longtext COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Index pour les tables exportées
--

--
-- Index pour la table `hymn`
--
ALTER TABLE `hymn`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `UNIQ_FEAF0A9ADC43AF6E` (`num`),
  ADD UNIQUE KEY `UNIQ_FEAF0A9AA52737CC` (`musical_part_id`);

--
-- Index pour la table `musical_part`
--
ALTER TABLE `musical_part`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT pour les tables exportées
--

--
-- AUTO_INCREMENT pour la table `hymn`
--
ALTER TABLE `hymn`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=75;
--
-- AUTO_INCREMENT pour la table `musical_part`
--
ALTER TABLE `musical_part`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
--
-- Contraintes pour les tables exportées
--

--
-- Contraintes pour la table `hymn`
--
ALTER TABLE `hymn`
  ADD CONSTRAINT `FK_FEAF0A9AA52737CC` FOREIGN KEY (`musical_part_id`) REFERENCES `musical_part` (`id`);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
