<?php

namespace Timothee\ModelBundle\Repository;

/**
 * HymnRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HymnRepository extends \Doctrine\ORM\EntityRepository
{
}
