<?php

namespace Timothee\ModelBundle\Repository;

/**
 * Musical_PartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Musical_PartRepository extends \Doctrine\ORM\EntityRepository
{
}
