<?php

namespace Timothee\ModelBundle\Repository;

/**
 * MusicalPartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MusicalPartRepository extends \Doctrine\ORM\EntityRepository
{
}
